CUDA_VISIBLE_DEVICES=0,1 python train.py\
    --model_name /media/HD0/lemon/bart-base-chinese\
    --train_path ../data/mix/mix_train.txt\
    --dev_path ../data/mix/mix_dev.txt\
    --seqlen 128\
    --number_of_gpu 8\
    --batch_size_per_gpu 16\
    --gradient_accumulation_steps 2\
    --effective_batch_size 256\
    --total_steps 400000\
    --print_every 1000\
    --save_every 10000\
    --learning_rate 2e-5\
    --margin 0.5\
    --save_path_prefix ./simctg_bart/
